import { defineStore } from 'pinia'
import { ref } from 'vue'

export type LanguageCode = 'zh' | 'en' | 'ru'

export const languageOptions = [
  { code: 'zh', label: '中文' },
  { code: 'en', label: 'English' },
  { code: 'ru', label: 'Русский' }
] as const

const STORAGE_KEY = 'university.admin.language'

const htmlLang: Record<LanguageCode, string> = {
  zh: 'zh-CN',
  en: 'en-US',
  ru: 'ru-RU'
}

const normalizeLanguage = (value: string | null): LanguageCode => {
  if (value === 'en' || value === 'ru') {
    return value
  }
  return 'zh'
}

const messages: Record<LanguageCode, Record<string, string>> = {
  zh: {
    'language.label': '语言',
    'common.signedIn': '已登录',
    'common.logout': '退出登录',
    'common.refreshData': '刷新数据',
    'common.refreshing': '刷新中...',
    'admin.login.eyebrow': '招生管理中心',
    'admin.login.title': '用更清晰的方式管理招生后台',
    'admin.login.subtitle': '集中审核报名、发布校园资讯，并维护院校、专业和成绩数据。',
    'admin.login.metricJwt': '安全令牌登录',
    'admin.login.metricBackend': '后端服务',
    'admin.login.metricWorkspace': '管理工作台',
    'admin.login.access': '管理员入口',
    'admin.login.formTitle': '登录运营后台',
    'admin.login.formCaption': '使用管理员账号和密码进入管理控制台。',
    'admin.login.username': '用户名',
    'admin.login.password': '密码',
    'admin.login.usernamePlaceholder': '请输入管理员用户名',
    'admin.login.passwordPlaceholder': '请输入密码',
    'admin.login.submit': '进入后台',
    'admin.login.submitting': '登录中...',
    'admin.login.error': '登录失败，请检查管理员账号和密码',
    'admin.panel.eyebrow': '运营工作台',
    'admin.panel.title': '大学招生后台',
    'admin.panel.subtitle': '院校、内容与学业数据集中管理。',
    'admin.section.dashboard.label': '概览',
    'admin.section.dashboard.title': '运营概览',
    'admin.section.dashboard.caption': '汇总与快捷操作',
    'admin.section.dashboard.description': '集中查看内容、目录增长和待处理招生审核。',
    'admin.section.students.label': '学生',
    'admin.section.students.title': '学生管理',
    'admin.section.students.caption': '维护学生资料',
    'admin.section.students.description': '新增、编辑和维护 student 表中的学生账号、个人信息和分数。',
    'admin.section.universities.label': '院校',
    'admin.section.universities.title': '院校目录',
    'admin.section.universities.caption': '管理院校与省份',
    'admin.section.universities.description': '维护院校记录、省份分类和学校元数据。',
    'admin.section.majors.label': '专业',
    'admin.section.majors.title': '专业目录',
    'admin.section.majors.caption': '专业与计划',
    'admin.section.majors.description': '维护专业代码、招生计划和课程信息。',
    'admin.section.applications.label': '报名审核',
    'admin.section.applications.title': '审核报名',
    'admin.section.applications.caption': '通过或拒绝提交',
    'admin.section.applications.description': '处理学生提交的院校和专业报名记录。',
    'admin.section.results.label': '结果',
    'admin.section.results.title': '录取与成绩',
    'admin.section.results.caption': '发布结果与分数',
    'admin.section.results.description': '维护学生中心使用的录取决定和学业成绩记录。',
    'admin.section.consultations.label': '咨询',
    'admin.section.consultations.title': '学生咨询回复',
    'admin.section.consultations.caption': '回答学生问题',
    'admin.section.consultations.description': '阅读学生问题并维护官方回复。',
    'admin.section.news.label': '资讯',
    'admin.section.news.title': '门户资讯',
    'admin.section.news.caption': '发布公告',
    'admin.section.news.description': '管理学生端公开显示的资讯内容。',
    'admin.section.pages.label': '页面',
    'admin.section.pages.title': '静态内容页面',
    'admin.section.pages.caption': '关于我们与系统介绍',
    'admin.section.pages.description': '编辑支撑平台说明的长内容页面。',
    'admin.section.settings.label': '设置',
    'admin.section.settings.title': '运行设置',
    'admin.section.settings.caption': '键值配置',
    'admin.section.settings.description': '维护平台使用的简单配置值。',
    'admin.section.ai.label': 'AI配置',
    'admin.section.ai.title': 'AI 对话配置',
    'admin.section.ai.caption': '通用 API 模板',
    'admin.section.ai.description': '配置学生端 AI 聊天使用的大模型 HTTP API、流式解析方式和提示词。',
    'admin.metrics.universities': '院校',
    'admin.metrics.provinceNote': '{count} 个省份已配置',
    'admin.metrics.students': '学生',
    'admin.metrics.studentNote': '学生表记录',
    'admin.metrics.majors': '专业',
    'admin.metrics.majorNote': '专业目录记录',
    'admin.metrics.pendingReviews': '待审核',
    'admin.metrics.pendingNote': '等待处理的招生审核',
    'admin.metrics.portalContent': '门户内容',
    'admin.metrics.contentNote': '资讯与静态页面',
    'common.search': '搜索',
    'common.actions': '操作',
    'common.edit': '编辑',
    'common.delete': '删除',
    'common.cancel': '取消',
    'common.remove': '移除',
    'common.noImage': '暂无图片',
    'common.applyFilter': '应用筛选',
    'common.status': '状态',
    'common.pending': '待审核',
    'common.approved': '已通过',
    'common.rejected': '已拒绝',
    'common.replied': '已回复',
    'common.reply': '回复',
    'common.editReply': '编辑回复',
    'common.uploading': '上传中...',
    'common.confirm': '确认',
    'common.requestFailed': '请求失败',
    'admin.message.uploadImageOnly': '请上传图片文件',
    'admin.message.imageUploaded': '图片上传成功',
    'admin.message.provinceRequired': '请输入省份名称',
    'admin.message.provinceUpdated': '省份已更新',
    'admin.message.provinceCreated': '省份已创建',
    'admin.message.deleteProvince': '确认删除该省份吗？',
    'admin.message.provinceDeleted': '省份已删除',
    'admin.message.studentRequired': '请输入学号、姓名，新建学生时还需要密码',
    'admin.message.studentUpdated': '学生信息已更新',
    'admin.message.studentCreated': '学生已创建',
    'admin.message.deleteStudent': '确认删除该学生吗？',
    'admin.message.studentDeleted': '学生已删除',
    'admin.message.universityRequired': '请输入院校名称并选择省份',
    'admin.message.universityUpdated': '院校已更新',
    'admin.message.universityCreated': '院校已创建',
    'admin.message.deleteUniversity': '确认删除该院校吗？',
    'admin.message.universityDeleted': '院校已删除',
    'admin.message.majorRequired': '请输入专业代码、专业名称并选择院校',
    'admin.message.majorUpdated': '专业已更新',
    'admin.message.majorCreated': '专业已创建',
    'admin.message.deleteMajor': '确认删除该专业吗？',
    'admin.message.majorDeleted': '专业已删除',
    'admin.message.newsRequired': '请输入资讯标题和内容',
    'admin.message.newsUpdated': '资讯已更新',
    'admin.message.newsCreated': '资讯已创建',
    'admin.message.deleteNews': '确认删除该资讯吗？',
    'admin.message.newsDeleted': '资讯已删除',
    'admin.message.pageRequired': '请输入页面标识、标题和内容',
    'admin.message.pageUpdated': '页面已更新',
    'admin.message.pageCreated': '页面已创建',
    'admin.message.deletePage': '确认删除该页面吗？',
    'admin.message.pageDeleted': '页面已删除',
    'admin.message.settingRequired': '请输入设置键',
    'admin.message.settingUpdated': '设置已更新',
    'admin.message.settingCreated': '设置已创建',
    'admin.message.deleteSetting': '确认删除该设置吗？',
    'admin.message.settingDeleted': '设置已删除',
    'admin.message.aiConfigSaved': 'AI 配置已保存',
    'admin.message.admissionResultRequired': '请输入报名编号并选择结果状态',
    'admin.message.admissionResultUpdated': '录取结果已更新',
    'admin.message.admissionResultCreated': '录取结果已创建',
    'admin.message.academicResultRequired': '请输入学生编号',
    'admin.message.academicResultUpdated': '成绩记录已更新',
    'admin.message.academicResultCreated': '成绩记录已创建',
    'admin.message.replyRequired': '请输入回复内容',
    'admin.message.replySubmitted': '回复已提交',
    'admin.message.reviewRequired': '请选择审核状态',
    'admin.message.reviewSubmitted': '审核已提交',
    'admin.dashboard.priorityQueue': '优先队列',
    'admin.dashboard.attentionTitle': '需要优先处理的事项',
    'admin.dashboard.pendingUniversity': '条院校报名等待审核。',
    'admin.dashboard.pendingMajor': '条专业报名仍在等待审核。',
    'admin.dashboard.newsAvailable': '条已发布资讯可在学生端查看。',
    'admin.dashboard.quickActions': '快捷操作',
    'admin.dashboard.nextTask': '直接进入下一项任务',
    'admin.dashboard.addUniversityTitle': '新增院校',
    'admin.dashboard.addUniversityText': '创建新的院校展示记录。',
    'admin.dashboard.addMajorTitle': '新增专业',
    'admin.dashboard.addMajorText': '发布新的专业方向。',
    'admin.dashboard.publishNewsTitle': '发布资讯',
    'admin.dashboard.publishNewsText': '向学生端推送更新。',
    'admin.dashboard.reviewApplicationsTitle': '审核报名',
    'admin.dashboard.reviewApplicationsText': '通过或拒绝待处理记录。',
    'admin.table.university': '院校',
    'admin.table.images': '图片',
    'admin.table.province': '省份',
    'admin.table.type': '类型',
    'admin.table.tier': '层次',
    'admin.table.phone': '电话',
    'admin.table.website': '官网',
    'admin.table.code': '代码',
    'admin.table.major': '专业',
    'admin.table.cover': '封面',
    'admin.table.duration': '学制',
    'admin.table.cutOff': '分数线',
    'admin.table.quota': '计划',
    'admin.table.registration': '报名号',
    'admin.table.student': '学生',
    'admin.table.studentNo': '学号',
    'admin.table.majorCode': '专业代码',
    'admin.table.comment': '备注',
    'admin.table.applicationId': '报名编号',
    'admin.table.result': '结果',
    'admin.table.feedback': '反馈',
    'admin.table.feedbackAt': '反馈时间',
    'admin.table.studentId': '学生编号',
    'admin.table.reportNo': '报告编号',
    'admin.table.grade': '成绩',
    'admin.table.evaluation': '评价',
    'admin.table.content': '内容',
    'admin.table.enteredAt': '录入时间',
    'admin.table.question': '问题',
    'admin.table.createdAt': '创建时间',
    'admin.table.title': '标题',
    'admin.table.image': '图片',
    'admin.table.introduction': '简介',
    'admin.table.publishedAt': '发布时间',
    'admin.table.slug': '标识',
    'admin.table.subtitle': '副标题',
    'admin.table.key': '键',
    'admin.table.value': '值',
    'admin.empty.universities': '暂无院校',
    'admin.empty.students': '暂无学生',
    'admin.empty.majors': '暂无专业',
    'admin.empty.universityApplications': '暂无院校报名',
    'admin.empty.majorApplications': '暂无专业报名',
    'admin.empty.admissionResults': '暂无录取结果',
    'admin.empty.academicResults': '暂无成绩记录',
    'admin.empty.consultations': '暂无咨询',
    'admin.empty.news': '暂无资讯',
    'admin.empty.pages': '暂无内容页面',
    'admin.empty.settings': '暂无设置',
    'admin.placeholder.universitySearch': '按院校名称搜索',
    'admin.placeholder.studentSearch': '按学号、姓名、学院或电话搜索',
    'admin.placeholder.studentPassword': '留空则保持当前密码',
    'admin.placeholder.majorSearch': '按专业名称或代码搜索',
    'admin.placeholder.newsSearch': '按资讯标题搜索',
    'admin.placeholder.statusFilter': '按状态筛选',
    'admin.placeholder.provinceName': '省份名称',
    'admin.placeholder.selectProvince': '选择省份',
    'admin.placeholder.selectUniversity': '选择院校',
    'admin.placeholder.selectResult': '选择结果',
    'admin.placeholder.selectDateTime': '选择日期时间',
    'admin.placeholder.selectDate': '选择日期',
    'admin.placeholder.reviewResult': '选择审核结果',
    'admin.action.manageProvinces': '管理省份',
    'admin.action.addStudent': '新增学生',
    'admin.action.addUniversity': '新增院校',
    'admin.action.addMajor': '新增专业',
    'admin.action.addNews': '新增资讯',
    'admin.action.addPage': '新增页面',
    'admin.action.addSetting': '新增设置',
    'admin.action.review': '审核',
    'admin.action.addAdmissionResult': '新增录取结果',
    'admin.action.addAcademicResult': '新增成绩记录',
    'admin.action.uploadImage': '上传图片',
    'admin.action.uploadCover': '上传封面',
    'admin.action.uploadPicture': '上传图片',
    'admin.action.saveStudent': '保存学生',
    'admin.action.saveUniversity': '保存院校',
    'admin.action.saveMajor': '保存专业',
    'admin.action.saveNews': '保存资讯',
    'admin.action.savePage': '保存页面',
    'admin.action.saveSetting': '保存设置',
    'admin.action.saveResult': '保存结果',
    'admin.action.submitReply': '提交回复',
    'admin.action.submitReview': '提交审核',
    'admin.action.saving': '保存中...',
    'admin.action.updateProvince': '更新省份',
    'admin.action.addProvince': '新增省份',
    'admin.results.description': '发布并维护来自当前数据库的结果记录。',
    'admin.pages.description': '编辑学生端展示的长内容页面。',
    'admin.settings.description': '维护新平台使用的系统键值配置。',
    'admin.ai.description': '使用通用 HTTP API 模板接入大模型。API Key 只会保存到后端，不会在页面中明文回显。',
    'admin.ai.enabled': '启用 AI',
    'admin.ai.providerName': '服务名称',
    'admin.ai.endpointUrl': '接口地址',
    'admin.ai.httpMethod': '请求方法',
    'admin.ai.apiKey': 'API Key',
    'admin.ai.apiKeySet': 'API Key 已配置；留空保存时会继续使用原密钥。',
    'admin.ai.apiKeyPlaceholder': '未配置 API Key',
    'admin.ai.keepApiKey': '留空保留当前密钥',
    'admin.ai.headersTemplate': '请求头模板 JSON',
    'admin.ai.bodyTemplate': '请求体模板 JSON',
    'admin.ai.model': '模型',
    'admin.ai.temperature': 'Temperature',
    'admin.ai.maxTokens': 'Max Tokens',
    'admin.ai.systemPrompt': '系统提示词',
    'admin.ai.streamProtocol': '流协议',
    'admin.ai.responseTextPath': '文本路径',
    'admin.ai.doneMarker': '结束标记',
    'admin.ai.timeoutSeconds': '超时秒数',
    'admin.ai.testMessage': '测试消息',
    'admin.ai.save': '保存配置',
    'admin.ai.test': '保存并测试',
    'admin.ai.testing': '测试中...',
    'admin.ai.testResult': '测试结果',
    'admin.ai.templatesInvalid': '请求头模板必须是合法 JSON。',
    'admin.ai.endpointRequired': '启用 AI 时必须填写接口地址。',
    'admin.tab.universityApplications': '院校报名',
    'admin.tab.majorApplications': '专业报名',
    'admin.tab.admissionResults': '录取结果',
    'admin.tab.academicResults': '成绩记录',
    'admin.dialog.manageProvinces': '管理省份',
    'admin.dialog.editStudent': '编辑学生',
    'admin.dialog.addStudent': '新增学生',
    'admin.dialog.editUniversity': '编辑院校',
    'admin.dialog.addUniversity': '新增院校',
    'admin.dialog.editMajor': '编辑专业',
    'admin.dialog.addMajor': '新增专业',
    'admin.dialog.editNews': '编辑资讯',
    'admin.dialog.publishNews': '发布资讯',
    'admin.dialog.editPage': '编辑页面',
    'admin.dialog.addPage': '新增页面',
    'admin.dialog.editSetting': '编辑设置',
    'admin.dialog.addSetting': '新增设置',
    'admin.dialog.editAdmissionResult': '编辑录取结果',
    'admin.dialog.addAdmissionResult': '新增录取结果',
    'admin.dialog.editAcademicResult': '编辑成绩记录',
    'admin.dialog.addAcademicResult': '新增成绩记录',
    'admin.dialog.replyConsultation': '回复咨询',
    'admin.dialog.reviewApplication': '审核报名',
    'admin.field.name': '名称',
    'admin.field.institutionType': '院校类型',
    'admin.field.universityImages': '院校图片',
    'admin.field.majorCode': '专业代码',
    'admin.field.majorName': '专业名称',
    'admin.field.cutOffScore': '分数线',
    'admin.field.enrollmentQuota': '招生计划',
    'admin.field.majorCoverImages': '专业封面图片',
    'admin.field.curriculum': '课程方案',
    'admin.field.newsPicture': '资讯图片',
    'admin.field.picture1': '图片 1',
    'admin.field.picture2': '图片 2',
    'admin.field.picture3': '图片 3',
    'admin.field.settingKey': '设置键',
    'admin.field.settingValue': '设置值',
    'admin.field.resultStatus': '结果状态',
    'admin.field.gradeEvaluation': '成绩评价',
    'admin.field.reportContent': '报告内容',
    'admin.field.studentQuestion': '学生问题',
    'admin.field.studentNo': '学号',
    'admin.field.password': '密码',
    'admin.field.studentName': '姓名',
    'admin.field.avatar': '头像路径',
    'admin.field.gender': '性别',
    'admin.field.college': '学院',
    'admin.field.contactNumber': '联系电话',
    'admin.field.score': '分数',
    'admin.field.reviewComment': '审核备注'
  },
  en: {
    'language.label': 'Language',
    'common.signedIn': 'Signed In',
    'common.logout': 'Log Out',
    'common.refreshData': 'Refresh Data',
    'common.refreshing': 'Refreshing...',
    'admin.login.eyebrow': 'Admissions Control Desk',
    'admin.login.title': 'University console with a sharper first impression.',
    'admin.login.subtitle': 'Review applications, publish campus updates, and coordinate enrollment from one place.',
    'admin.login.metricJwt': 'Secure JWT sign-in',
    'admin.login.metricBackend': 'Spring Boot 3 backend',
    'admin.login.metricWorkspace': 'Vue 3 admin workspace',
    'admin.login.access': 'Admin Access',
    'admin.login.formTitle': 'Sign in to the operations panel',
    'admin.login.formCaption': 'Use your administrator credentials to access the management console.',
    'admin.login.username': 'Username',
    'admin.login.password': 'Password',
    'admin.login.usernamePlaceholder': 'Enter admin username',
    'admin.login.passwordPlaceholder': 'Enter password',
    'admin.login.submit': 'Enter Console',
    'admin.login.submitting': 'Signing in...',
    'admin.login.error': 'Login failed. Please check the administrator username and password.',
    'admin.panel.eyebrow': 'Operations Panel',
    'admin.panel.title': 'University Admin',
    'admin.panel.subtitle': 'Admissions, content, and academic data in one place.',
    'admin.section.dashboard.label': 'Dashboard',
    'admin.section.dashboard.title': 'Operational overview',
    'admin.section.dashboard.caption': 'Summary and quick actions',
    'admin.section.dashboard.description': 'Track content, catalog growth, and pending admissions work from a single cockpit.',
    'admin.section.students.label': 'Students',
    'admin.section.students.title': 'Student management',
    'admin.section.students.caption': 'Maintain student records',
    'admin.section.students.description': 'Create and edit student accounts, personal data, and scores stored in the student table.',
    'admin.section.universities.label': 'Universities',
    'admin.section.universities.title': 'University catalog',
    'admin.section.universities.caption': 'Manage schools and provinces',
    'admin.section.universities.description': 'Create and maintain university records, region taxonomy, and school metadata.',
    'admin.section.majors.label': 'Majors',
    'admin.section.majors.title': 'Major directory',
    'admin.section.majors.caption': 'Programs and quotas',
    'admin.section.majors.description': 'Maintain program codes, quotas, and curriculum-facing information.',
    'admin.section.applications.label': 'Applications',
    'admin.section.applications.title': 'Review applications',
    'admin.section.applications.caption': 'Approve and reject submissions',
    'admin.section.applications.description': 'Handle student submissions for universities and majors without digging through raw records.',
    'admin.section.results.label': 'Results',
    'admin.section.results.title': 'Admission and academic results',
    'admin.section.results.caption': 'Publish outcomes and scores',
    'admin.section.results.description': 'Maintain admission decisions and academic result records used by the student center.',
    'admin.section.consultations.label': 'Consultations',
    'admin.section.consultations.title': 'Student consultation replies',
    'admin.section.consultations.caption': 'Answer student questions',
    'admin.section.consultations.description': 'Read student questions and maintain official reply records without leaving the admin console.',
    'admin.section.news.label': 'News',
    'admin.section.news.title': 'Portal news',
    'admin.section.news.caption': 'Publish announcements',
    'admin.section.news.description': 'Manage the content feed that students see on the public portal.',
    'admin.section.pages.label': 'Pages',
    'admin.section.pages.title': 'Static content pages',
    'admin.section.pages.caption': 'About us and system intro',
    'admin.section.pages.description': 'Edit the long-form site pages that support the platform narrative.',
    'admin.section.settings.label': 'Settings',
    'admin.section.settings.title': 'Runtime settings',
    'admin.section.settings.caption': 'Key-value configuration',
    'admin.section.settings.description': 'Maintain simple configuration values exposed through the new platform.',
    'admin.section.ai.label': 'AI Config',
    'admin.section.ai.title': 'AI Chat Config',
    'admin.section.ai.caption': 'Generic API template',
    'admin.section.ai.description': 'Configure the HTTP model API, streaming parser, and prompts used by student AI chat.',
    'admin.metrics.universities': 'Universities',
    'admin.metrics.provinceNote': '{count} provinces configured',
    'admin.metrics.students': 'Students',
    'admin.metrics.studentNote': 'Student table records',
    'admin.metrics.majors': 'Majors',
    'admin.metrics.majorNote': 'Program directory entries',
    'admin.metrics.pendingReviews': 'Pending Reviews',
    'admin.metrics.pendingNote': 'Admissions decisions waiting',
    'admin.metrics.portalContent': 'Portal Content',
    'admin.metrics.contentNote': 'News articles and static pages',
    'common.search': 'Search',
    'common.actions': 'Actions',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.cancel': 'Cancel',
    'common.remove': 'Remove',
    'common.noImage': 'No image',
    'common.applyFilter': 'Apply Filter',
    'common.status': 'Status',
    'common.pending': 'Pending',
    'common.approved': 'Approved',
    'common.rejected': 'Rejected',
    'common.replied': 'Replied',
    'common.reply': 'Reply',
    'common.editReply': 'Edit reply',
    'common.uploading': 'Uploading...',
    'common.confirm': 'Confirm',
    'common.requestFailed': 'Request failed',
    'admin.message.uploadImageOnly': 'Please upload an image file',
    'admin.message.imageUploaded': 'Image uploaded',
    'admin.message.provinceRequired': 'Province name is required',
    'admin.message.provinceUpdated': 'Province updated',
    'admin.message.provinceCreated': 'Province created',
    'admin.message.deleteProvince': 'Delete this province?',
    'admin.message.provinceDeleted': 'Province deleted',
    'admin.message.studentRequired': 'Student number and name are required. Password is required for new students.',
    'admin.message.studentUpdated': 'Student updated',
    'admin.message.studentCreated': 'Student created',
    'admin.message.deleteStudent': 'Delete this student?',
    'admin.message.studentDeleted': 'Student deleted',
    'admin.message.universityRequired': 'University name and province are required',
    'admin.message.universityUpdated': 'University updated',
    'admin.message.universityCreated': 'University created',
    'admin.message.deleteUniversity': 'Delete this university?',
    'admin.message.universityDeleted': 'University deleted',
    'admin.message.majorRequired': 'Major code, name, and university are required',
    'admin.message.majorUpdated': 'Major updated',
    'admin.message.majorCreated': 'Major created',
    'admin.message.deleteMajor': 'Delete this major?',
    'admin.message.majorDeleted': 'Major deleted',
    'admin.message.newsRequired': 'News title and content are required',
    'admin.message.newsUpdated': 'News updated',
    'admin.message.newsCreated': 'News created',
    'admin.message.deleteNews': 'Delete this news article?',
    'admin.message.newsDeleted': 'News deleted',
    'admin.message.pageRequired': 'Slug, title, and content are required',
    'admin.message.pageUpdated': 'Page updated',
    'admin.message.pageCreated': 'Page created',
    'admin.message.deletePage': 'Delete this page?',
    'admin.message.pageDeleted': 'Page deleted',
    'admin.message.settingRequired': 'Setting key is required',
    'admin.message.settingUpdated': 'Setting updated',
    'admin.message.settingCreated': 'Setting created',
    'admin.message.deleteSetting': 'Delete this setting?',
    'admin.message.settingDeleted': 'Setting deleted',
    'admin.message.aiConfigSaved': 'AI configuration saved',
    'admin.message.admissionResultRequired': 'Application ID and result status are required',
    'admin.message.admissionResultUpdated': 'Admission result updated',
    'admin.message.admissionResultCreated': 'Admission result created',
    'admin.message.academicResultRequired': 'Student ID is required',
    'admin.message.academicResultUpdated': 'Academic result updated',
    'admin.message.academicResultCreated': 'Academic result created',
    'admin.message.replyRequired': 'Reply is required',
    'admin.message.replySubmitted': 'Reply submitted',
    'admin.message.reviewRequired': 'Review status is required',
    'admin.message.reviewSubmitted': 'Review submitted',
    'admin.dashboard.priorityQueue': 'Priority Queue',
    'admin.dashboard.attentionTitle': 'What needs attention first',
    'admin.dashboard.pendingUniversity': 'university applications are waiting for review.',
    'admin.dashboard.pendingMajor': 'major applications are still pending.',
    'admin.dashboard.newsAvailable': 'published news items are available for the portal.',
    'admin.dashboard.quickActions': 'Quick Actions',
    'admin.dashboard.nextTask': 'Jump into the next task',
    'admin.dashboard.addUniversityTitle': 'Add university',
    'admin.dashboard.addUniversityText': 'Create a new school listing.',
    'admin.dashboard.addMajorTitle': 'Add major',
    'admin.dashboard.addMajorText': 'Publish a new program offering.',
    'admin.dashboard.publishNewsTitle': 'Publish news',
    'admin.dashboard.publishNewsText': 'Push updates to the student portal.',
    'admin.dashboard.reviewApplicationsTitle': 'Review applications',
    'admin.dashboard.reviewApplicationsText': 'Approve or reject pending records.',
    'admin.table.university': 'University',
    'admin.table.images': 'Images',
    'admin.table.province': 'Province',
    'admin.table.type': 'Type',
    'admin.table.tier': 'Tier',
    'admin.table.phone': 'Phone',
    'admin.table.website': 'Website',
    'admin.table.code': 'Code',
    'admin.table.major': 'Major',
    'admin.table.cover': 'Cover',
    'admin.table.duration': 'Duration',
    'admin.table.cutOff': 'Cut Off',
    'admin.table.quota': 'Quota',
    'admin.table.registration': 'Registration',
    'admin.table.student': 'Student',
    'admin.table.studentNo': 'Student No.',
    'admin.table.majorCode': 'Major Code',
    'admin.table.comment': 'Comment',
    'admin.table.applicationId': 'Application ID',
    'admin.table.result': 'Result',
    'admin.table.feedback': 'Feedback',
    'admin.table.feedbackAt': 'Feedback At',
    'admin.table.studentId': 'Student ID',
    'admin.table.reportNo': 'Report No.',
    'admin.table.grade': 'Grade',
    'admin.table.evaluation': 'Evaluation',
    'admin.table.content': 'Content',
    'admin.table.enteredAt': 'Entered At',
    'admin.table.question': 'Question',
    'admin.table.createdAt': 'Created At',
    'admin.table.title': 'Title',
    'admin.table.image': 'Image',
    'admin.table.introduction': 'Introduction',
    'admin.table.publishedAt': 'Published At',
    'admin.table.slug': 'Slug',
    'admin.table.subtitle': 'Subtitle',
    'admin.table.key': 'Key',
    'admin.table.value': 'Value',
    'admin.empty.universities': 'No universities found',
    'admin.empty.students': 'No students found',
    'admin.empty.majors': 'No majors found',
    'admin.empty.universityApplications': 'No university applications',
    'admin.empty.majorApplications': 'No major applications',
    'admin.empty.admissionResults': 'No admission results',
    'admin.empty.academicResults': 'No academic results',
    'admin.empty.consultations': 'No consultations',
    'admin.empty.news': 'No news articles',
    'admin.empty.pages': 'No content pages',
    'admin.empty.settings': 'No settings yet',
    'admin.placeholder.universitySearch': 'Search by university name',
    'admin.placeholder.studentSearch': 'Search by student number, name, college, or phone',
    'admin.placeholder.studentPassword': 'Leave blank to keep current password',
    'admin.placeholder.majorSearch': 'Search by major name or code',
    'admin.placeholder.newsSearch': 'Search by news title',
    'admin.placeholder.statusFilter': 'Filter by status',
    'admin.placeholder.provinceName': 'Province name',
    'admin.placeholder.selectProvince': 'Select province',
    'admin.placeholder.selectUniversity': 'Select university',
    'admin.placeholder.selectResult': 'Select result',
    'admin.placeholder.selectDateTime': 'Select date time',
    'admin.placeholder.selectDate': 'Select date',
    'admin.placeholder.reviewResult': 'Select review result',
    'admin.action.manageProvinces': 'Manage provinces',
    'admin.action.addStudent': 'Add student',
    'admin.action.addUniversity': 'Add university',
    'admin.action.addMajor': 'Add major',
    'admin.action.addNews': 'Add news',
    'admin.action.addPage': 'Add page',
    'admin.action.addSetting': 'Add setting',
    'admin.action.review': 'Review',
    'admin.action.addAdmissionResult': 'Add admission result',
    'admin.action.addAcademicResult': 'Add academic result',
    'admin.action.uploadImage': 'Upload Image',
    'admin.action.uploadCover': 'Upload Cover',
    'admin.action.uploadPicture': 'Upload Picture',
    'admin.action.saveStudent': 'Save Student',
    'admin.action.saveUniversity': 'Save University',
    'admin.action.saveMajor': 'Save Major',
    'admin.action.saveNews': 'Save News',
    'admin.action.savePage': 'Save Page',
    'admin.action.saveSetting': 'Save Setting',
    'admin.action.saveResult': 'Save Result',
    'admin.action.submitReply': 'Submit Reply',
    'admin.action.submitReview': 'Submit Review',
    'admin.action.saving': 'Saving...',
    'admin.action.updateProvince': 'Update Province',
    'admin.action.addProvince': 'Add Province',
    'admin.results.description': 'Publish and maintain result records backed by the running database.',
    'admin.pages.description': 'Edit the long-form pages shown in the portal.',
    'admin.settings.description': 'System key-value pairs exposed through the new platform.',
    'admin.ai.description': 'Connect any model through a generic HTTP API template. The API key is stored by the backend and is never shown in plain text.',
    'admin.ai.enabled': 'Enable AI',
    'admin.ai.providerName': 'Provider Name',
    'admin.ai.endpointUrl': 'Endpoint URL',
    'admin.ai.httpMethod': 'HTTP Method',
    'admin.ai.apiKey': 'API Key',
    'admin.ai.apiKeySet': 'API Key is configured. Leave this field empty to keep the current key.',
    'admin.ai.apiKeyPlaceholder': 'API Key is not configured',
    'admin.ai.keepApiKey': 'Leave empty to keep current key',
    'admin.ai.headersTemplate': 'Headers Template JSON',
    'admin.ai.bodyTemplate': 'Body Template JSON',
    'admin.ai.model': 'Model',
    'admin.ai.temperature': 'Temperature',
    'admin.ai.maxTokens': 'Max Tokens',
    'admin.ai.systemPrompt': 'System Prompt',
    'admin.ai.streamProtocol': 'Stream Protocol',
    'admin.ai.responseTextPath': 'Text Path',
    'admin.ai.doneMarker': 'Done Marker',
    'admin.ai.timeoutSeconds': 'Timeout Seconds',
    'admin.ai.testMessage': 'Test Message',
    'admin.ai.save': 'Save Config',
    'admin.ai.test': 'Save and Test',
    'admin.ai.testing': 'Testing...',
    'admin.ai.testResult': 'Test Result',
    'admin.ai.templatesInvalid': 'Headers template must be valid JSON.',
    'admin.ai.endpointRequired': 'Endpoint URL is required when AI is enabled.',
    'admin.tab.universityApplications': 'University Applications',
    'admin.tab.majorApplications': 'Major Applications',
    'admin.tab.admissionResults': 'Admission Results',
    'admin.tab.academicResults': 'Academic Results',
    'admin.dialog.manageProvinces': 'Manage Provinces',
    'admin.dialog.editStudent': 'Edit Student',
    'admin.dialog.addStudent': 'Add Student',
    'admin.dialog.editUniversity': 'Edit University',
    'admin.dialog.addUniversity': 'Add University',
    'admin.dialog.editMajor': 'Edit Major',
    'admin.dialog.addMajor': 'Add Major',
    'admin.dialog.editNews': 'Edit News',
    'admin.dialog.publishNews': 'Publish News',
    'admin.dialog.editPage': 'Edit Page',
    'admin.dialog.addPage': 'Add Page',
    'admin.dialog.editSetting': 'Edit Setting',
    'admin.dialog.addSetting': 'Add Setting',
    'admin.dialog.editAdmissionResult': 'Edit Admission Result',
    'admin.dialog.addAdmissionResult': 'Add Admission Result',
    'admin.dialog.editAcademicResult': 'Edit Academic Result',
    'admin.dialog.addAcademicResult': 'Add Academic Result',
    'admin.dialog.replyConsultation': 'Reply Consultation',
    'admin.dialog.reviewApplication': 'Review Application',
    'admin.field.name': 'Name',
    'admin.field.institutionType': 'Institution Type',
    'admin.field.universityImages': 'University Images',
    'admin.field.majorCode': 'Major Code',
    'admin.field.majorName': 'Major Name',
    'admin.field.cutOffScore': 'Cut Off Score',
    'admin.field.enrollmentQuota': 'Enrollment Quota',
    'admin.field.majorCoverImages': 'Major Cover Images',
    'admin.field.curriculum': 'Curriculum',
    'admin.field.newsPicture': 'News Picture',
    'admin.field.picture1': 'Picture 1',
    'admin.field.picture2': 'Picture 2',
    'admin.field.picture3': 'Picture 3',
    'admin.field.settingKey': 'Setting Key',
    'admin.field.settingValue': 'Setting Value',
    'admin.field.resultStatus': 'Result Status',
    'admin.field.gradeEvaluation': 'Grade Evaluation',
    'admin.field.reportContent': 'Report Content',
    'admin.field.studentQuestion': 'Student Question',
    'admin.field.studentNo': 'Student No.',
    'admin.field.password': 'Password',
    'admin.field.studentName': 'Name',
    'admin.field.avatar': 'Avatar Path',
    'admin.field.gender': 'Gender',
    'admin.field.college': 'College',
    'admin.field.contactNumber': 'Contact Number',
    'admin.field.score': 'Score',
    'admin.field.reviewComment': 'Review Comment'
  },
  ru: {
    'language.label': 'Язык',
    'common.signedIn': 'Вход выполнен',
    'common.logout': 'Выйти',
    'common.refreshData': 'Обновить данные',
    'common.refreshing': 'Обновление...',
    'admin.login.eyebrow': 'Панель управления приемом',
    'admin.login.title': 'Панель управления приемом с понятным первым экраном.',
    'admin.login.subtitle': 'Проверяйте заявки, публикуйте новости кампуса и координируйте прием из одного места.',
    'admin.login.metricJwt': 'Безопасный вход по токену',
    'admin.login.metricBackend': 'Серверная часть',
    'admin.login.metricWorkspace': 'Административная панель',
    'admin.login.access': 'Доступ администратора',
    'admin.login.formTitle': 'Вход в операционную панель',
    'admin.login.formCaption': 'Используйте учетные данные администратора для доступа к консоли.',
    'admin.login.username': 'Имя пользователя',
    'admin.login.password': 'Пароль',
    'admin.login.usernamePlaceholder': 'Введите имя администратора',
    'admin.login.passwordPlaceholder': 'Введите пароль',
    'admin.login.submit': 'Войти в консоль',
    'admin.login.submitting': 'Вход...',
    'admin.login.error': 'Не удалось войти. Проверьте имя администратора и пароль.',
    'admin.panel.eyebrow': 'Операционная панель',
    'admin.panel.title': 'Администрирование вуза',
    'admin.panel.subtitle': 'Прием, контент и учебные данные в одном месте.',
    'admin.section.dashboard.label': 'Обзор',
    'admin.section.dashboard.title': 'Операционный обзор',
    'admin.section.dashboard.caption': 'Сводка и быстрые действия',
    'admin.section.dashboard.description': 'Отслеживайте контент, рост каталога и ожидающие проверки заявок.',
    'admin.section.students.label': 'Студенты',
    'admin.section.students.title': 'Управление студентами',
    'admin.section.students.caption': 'Ведение данных студентов',
    'admin.section.students.description': 'Создавайте и редактируйте учетные записи, данные и баллы из таблицы student.',
    'admin.section.universities.label': 'Вузы',
    'admin.section.universities.title': 'Каталог вузов',
    'admin.section.universities.caption': 'Управление вузами и провинциями',
    'admin.section.universities.description': 'Создавайте и поддерживайте записи вузов, регионы и метаданные.',
    'admin.section.majors.label': 'Специальности',
    'admin.section.majors.title': 'Каталог специальностей',
    'admin.section.majors.caption': 'Программы и квоты',
    'admin.section.majors.description': 'Поддерживайте коды программ, квоты и информацию об учебном плане.',
    'admin.section.applications.label': 'Заявки',
    'admin.section.applications.title': 'Проверка заявок',
    'admin.section.applications.caption': 'Одобрение и отклонение',
    'admin.section.applications.description': 'Обрабатывайте заявки студентов в вузы и на специальности.',
    'admin.section.results.label': 'Результаты',
    'admin.section.results.title': 'Зачисление и оценки',
    'admin.section.results.caption': 'Публикация решений и баллов',
    'admin.section.results.description': 'Поддерживайте решения о зачислении и учебные результаты для кабинета студента.',
    'admin.section.consultations.label': 'Вопросы',
    'admin.section.consultations.title': 'Ответы на вопросы студентов',
    'admin.section.consultations.caption': 'Ответы студентам',
    'admin.section.consultations.description': 'Читайте вопросы студентов и ведите официальные ответы.',
    'admin.section.news.label': 'Новости',
    'admin.section.news.title': 'Новости портала',
    'admin.section.news.caption': 'Публикация объявлений',
    'admin.section.news.description': 'Управляйте новостной лентой, которую видят студенты.',
    'admin.section.pages.label': 'Страницы',
    'admin.section.pages.title': 'Статические страницы',
    'admin.section.pages.caption': 'О нас и о системе',
    'admin.section.pages.description': 'Редактируйте длинные страницы с описанием платформы.',
    'admin.section.settings.label': 'Настройки',
    'admin.section.settings.title': 'Рабочие настройки',
    'admin.section.settings.caption': 'Конфигурация ключ-значение',
    'admin.section.settings.description': 'Поддерживайте простые настройки платформы.',
    'admin.section.ai.label': 'AI-настройки',
    'admin.section.ai.title': 'Настройки AI-чата',
    'admin.section.ai.caption': 'Универсальный шаблон API',
    'admin.section.ai.description': 'Настройте HTTP API модели, потоковый разбор и подсказки для студенческого AI-чата.',
    'admin.metrics.universities': 'Вузы',
    'admin.metrics.provinceNote': '{count} провинций настроено',
    'admin.metrics.students': 'Студенты',
    'admin.metrics.studentNote': 'Записи таблицы студентов',
    'admin.metrics.majors': 'Специальности',
    'admin.metrics.majorNote': 'Записи каталога программ',
    'admin.metrics.pendingReviews': 'На проверке',
    'admin.metrics.pendingNote': 'Ожидающие решения по приему',
    'admin.metrics.portalContent': 'Контент портала',
    'admin.metrics.contentNote': 'Новости и статические страницы',
    'common.search': 'Поиск',
    'common.actions': 'Действия',
    'common.edit': 'Изменить',
    'common.delete': 'Удалить',
    'common.cancel': 'Отмена',
    'common.remove': 'Удалить',
    'common.noImage': 'Нет изображения',
    'common.applyFilter': 'Применить фильтр',
    'common.status': 'Статус',
    'common.pending': 'На проверке',
    'common.approved': 'Одобрено',
    'common.rejected': 'Отклонено',
    'common.replied': 'Отвечено',
    'common.reply': 'Ответить',
    'common.editReply': 'Изменить ответ',
    'common.uploading': 'Загрузка...',
    'common.confirm': 'Подтвердить',
    'common.requestFailed': 'Запрос не выполнен',
    'admin.message.uploadImageOnly': 'Загрузите файл изображения',
    'admin.message.imageUploaded': 'Изображение загружено',
    'admin.message.provinceRequired': 'Укажите название провинции',
    'admin.message.provinceUpdated': 'Провинция обновлена',
    'admin.message.provinceCreated': 'Провинция создана',
    'admin.message.deleteProvince': 'Удалить эту провинцию?',
    'admin.message.provinceDeleted': 'Провинция удалена',
    'admin.message.studentRequired': 'Укажите номер студента и имя. Для нового студента нужен пароль.',
    'admin.message.studentUpdated': 'Данные студента обновлены',
    'admin.message.studentCreated': 'Студент создан',
    'admin.message.deleteStudent': 'Удалить этого студента?',
    'admin.message.studentDeleted': 'Студент удален',
    'admin.message.universityRequired': 'Укажите название вуза и выберите провинцию',
    'admin.message.universityUpdated': 'Вуз обновлен',
    'admin.message.universityCreated': 'Вуз создан',
    'admin.message.deleteUniversity': 'Удалить этот вуз?',
    'admin.message.universityDeleted': 'Вуз удален',
    'admin.message.majorRequired': 'Укажите код, название специальности и выберите вуз',
    'admin.message.majorUpdated': 'Специальность обновлена',
    'admin.message.majorCreated': 'Специальность создана',
    'admin.message.deleteMajor': 'Удалить эту специальность?',
    'admin.message.majorDeleted': 'Специальность удалена',
    'admin.message.newsRequired': 'Укажите заголовок и содержание новости',
    'admin.message.newsUpdated': 'Новость обновлена',
    'admin.message.newsCreated': 'Новость создана',
    'admin.message.deleteNews': 'Удалить эту новость?',
    'admin.message.newsDeleted': 'Новость удалена',
    'admin.message.pageRequired': 'Укажите идентификатор, заголовок и содержание страницы',
    'admin.message.pageUpdated': 'Страница обновлена',
    'admin.message.pageCreated': 'Страница создана',
    'admin.message.deletePage': 'Удалить эту страницу?',
    'admin.message.pageDeleted': 'Страница удалена',
    'admin.message.settingRequired': 'Укажите ключ настройки',
    'admin.message.settingUpdated': 'Настройка обновлена',
    'admin.message.settingCreated': 'Настройка создана',
    'admin.message.deleteSetting': 'Удалить эту настройку?',
    'admin.message.settingDeleted': 'Настройка удалена',
    'admin.message.aiConfigSaved': 'AI-настройки сохранены',
    'admin.message.admissionResultRequired': 'Укажите номер заявки и статус результата',
    'admin.message.admissionResultUpdated': 'Результат зачисления обновлен',
    'admin.message.admissionResultCreated': 'Результат зачисления создан',
    'admin.message.academicResultRequired': 'Укажите номер студента',
    'admin.message.academicResultUpdated': 'Запись оценок обновлена',
    'admin.message.academicResultCreated': 'Запись оценок создана',
    'admin.message.replyRequired': 'Введите текст ответа',
    'admin.message.replySubmitted': 'Ответ отправлен',
    'admin.message.reviewRequired': 'Выберите статус проверки',
    'admin.message.reviewSubmitted': 'Проверка отправлена',
    'admin.dashboard.priorityQueue': 'Приоритетная очередь',
    'admin.dashboard.attentionTitle': 'Что требует внимания в первую очередь',
    'admin.dashboard.pendingUniversity': 'заявок в вузы ожидают проверки.',
    'admin.dashboard.pendingMajor': 'заявок на специальности все еще ожидают проверки.',
    'admin.dashboard.newsAvailable': 'опубликованных новостей доступны на портале.',
    'admin.dashboard.quickActions': 'Быстрые действия',
    'admin.dashboard.nextTask': 'Перейти к следующей задаче',
    'admin.dashboard.addUniversityTitle': 'Добавить вуз',
    'admin.dashboard.addUniversityText': 'Создать новую запись вуза.',
    'admin.dashboard.addMajorTitle': 'Добавить специальность',
    'admin.dashboard.addMajorText': 'Опубликовать новое направление.',
    'admin.dashboard.publishNewsTitle': 'Опубликовать новость',
    'admin.dashboard.publishNewsText': 'Отправить обновления на портал студента.',
    'admin.dashboard.reviewApplicationsTitle': 'Проверить заявки',
    'admin.dashboard.reviewApplicationsText': 'Одобрить или отклонить ожидающие записи.',
    'admin.table.university': 'Вуз',
    'admin.table.images': 'Изображения',
    'admin.table.province': 'Провинция',
    'admin.table.type': 'Тип',
    'admin.table.tier': 'Уровень',
    'admin.table.phone': 'Телефон',
    'admin.table.website': 'Сайт',
    'admin.table.code': 'Код',
    'admin.table.major': 'Специальность',
    'admin.table.cover': 'Обложка',
    'admin.table.duration': 'Срок',
    'admin.table.cutOff': 'Проходной балл',
    'admin.table.quota': 'План',
    'admin.table.registration': 'Регистрация',
    'admin.table.student': 'Студент',
    'admin.table.studentNo': 'Номер студента',
    'admin.table.majorCode': 'Код специальности',
    'admin.table.comment': 'Комментарий',
    'admin.table.applicationId': 'Номер заявки',
    'admin.table.result': 'Результат',
    'admin.table.feedback': 'Отзыв',
    'admin.table.feedbackAt': 'Время отзыва',
    'admin.table.studentId': 'Номер студента',
    'admin.table.reportNo': 'Номер отчета',
    'admin.table.grade': 'Оценка',
    'admin.table.evaluation': 'Оценивание',
    'admin.table.content': 'Контент',
    'admin.table.enteredAt': 'Дата ввода',
    'admin.table.question': 'Вопрос',
    'admin.table.createdAt': 'Создано',
    'admin.table.title': 'Заголовок',
    'admin.table.image': 'Изображение',
    'admin.table.introduction': 'Введение',
    'admin.table.publishedAt': 'Опубликовано',
    'admin.table.slug': 'Идентификатор',
    'admin.table.subtitle': 'Подзаголовок',
    'admin.table.key': 'Ключ',
    'admin.table.value': 'Значение',
    'admin.empty.universities': 'Вузы не найдены',
    'admin.empty.students': 'Студенты не найдены',
    'admin.empty.majors': 'Специальности не найдены',
    'admin.empty.universityApplications': 'Заявок в вузы нет',
    'admin.empty.majorApplications': 'Заявок на специальности нет',
    'admin.empty.admissionResults': 'Результатов зачисления нет',
    'admin.empty.academicResults': 'Записей оценок нет',
    'admin.empty.consultations': 'Консультаций нет',
    'admin.empty.news': 'Новостей нет',
    'admin.empty.pages': 'Страниц контента нет',
    'admin.empty.settings': 'Настроек пока нет',
    'admin.placeholder.universitySearch': 'Поиск по названию вуза',
    'admin.placeholder.studentSearch': 'Поиск по номеру, имени, факультету или телефону',
    'admin.placeholder.studentPassword': 'Оставьте пустым, чтобы сохранить текущий пароль',
    'admin.placeholder.majorSearch': 'Поиск по специальности или коду',
    'admin.placeholder.newsSearch': 'Поиск по заголовку новости',
    'admin.placeholder.statusFilter': 'Фильтр по статусу',
    'admin.placeholder.provinceName': 'Название провинции',
    'admin.placeholder.selectProvince': 'Выберите провинцию',
    'admin.placeholder.selectUniversity': 'Выберите вуз',
    'admin.placeholder.selectResult': 'Выберите результат',
    'admin.placeholder.selectDateTime': 'Выберите дату и время',
    'admin.placeholder.selectDate': 'Выберите дату',
    'admin.placeholder.reviewResult': 'Выберите результат проверки',
    'admin.action.manageProvinces': 'Управление провинциями',
    'admin.action.addStudent': 'Добавить студента',
    'admin.action.addUniversity': 'Добавить вуз',
    'admin.action.addMajor': 'Добавить специальность',
    'admin.action.addNews': 'Добавить новость',
    'admin.action.addPage': 'Добавить страницу',
    'admin.action.addSetting': 'Добавить настройку',
    'admin.action.review': 'Проверить',
    'admin.action.addAdmissionResult': 'Добавить результат зачисления',
    'admin.action.addAcademicResult': 'Добавить запись оценок',
    'admin.action.uploadImage': 'Загрузить изображение',
    'admin.action.uploadCover': 'Загрузить обложку',
    'admin.action.uploadPicture': 'Загрузить изображение',
    'admin.action.saveStudent': 'Сохранить студента',
    'admin.action.saveUniversity': 'Сохранить вуз',
    'admin.action.saveMajor': 'Сохранить специальность',
    'admin.action.saveNews': 'Сохранить новость',
    'admin.action.savePage': 'Сохранить страницу',
    'admin.action.saveSetting': 'Сохранить настройку',
    'admin.action.saveResult': 'Сохранить результат',
    'admin.action.submitReply': 'Отправить ответ',
    'admin.action.submitReview': 'Отправить проверку',
    'admin.action.saving': 'Сохранение...',
    'admin.action.updateProvince': 'Обновить провинцию',
    'admin.action.addProvince': 'Добавить провинцию',
    'admin.results.description': 'Публикуйте и поддерживайте записи результатов из текущей базы данных.',
    'admin.pages.description': 'Редактируйте длинные страницы, отображаемые на портале.',
    'admin.settings.description': 'Системные пары ключ-значение новой платформы.',
    'admin.ai.description': 'Подключайте любую модель через универсальный шаблон HTTP API. API Key хранится на сервере и не показывается открытым текстом.',
    'admin.ai.enabled': 'Включить AI',
    'admin.ai.providerName': 'Название сервиса',
    'admin.ai.endpointUrl': 'URL интерфейса',
    'admin.ai.httpMethod': 'Метод запроса',
    'admin.ai.apiKey': 'API Key',
    'admin.ai.apiKeySet': 'API Key настроен. Оставьте поле пустым, чтобы сохранить текущий ключ.',
    'admin.ai.apiKeyPlaceholder': 'API Key не настроен',
    'admin.ai.keepApiKey': 'Оставьте пустым, чтобы сохранить ключ',
    'admin.ai.headersTemplate': 'JSON шаблона заголовков',
    'admin.ai.bodyTemplate': 'JSON шаблона тела запроса',
    'admin.ai.model': 'Модель',
    'admin.ai.temperature': 'Temperature',
    'admin.ai.maxTokens': 'Max Tokens',
    'admin.ai.systemPrompt': 'Системная подсказка',
    'admin.ai.streamProtocol': 'Потоковый протокол',
    'admin.ai.responseTextPath': 'Путь к тексту',
    'admin.ai.doneMarker': 'Маркер завершения',
    'admin.ai.timeoutSeconds': 'Таймаут в секундах',
    'admin.ai.testMessage': 'Тестовое сообщение',
    'admin.ai.save': 'Сохранить',
    'admin.ai.test': 'Сохранить и проверить',
    'admin.ai.testing': 'Проверка...',
    'admin.ai.testResult': 'Результат проверки',
    'admin.ai.templatesInvalid': 'Шаблон заголовков должен быть корректным JSON.',
    'admin.ai.endpointRequired': 'При включенном AI нужно указать URL интерфейса.',
    'admin.tab.universityApplications': 'Заявки в вузы',
    'admin.tab.majorApplications': 'Заявки на специальности',
    'admin.tab.admissionResults': 'Результаты зачисления',
    'admin.tab.academicResults': 'Записи оценок',
    'admin.dialog.manageProvinces': 'Управление провинциями',
    'admin.dialog.editStudent': 'Изменить студента',
    'admin.dialog.addStudent': 'Добавить студента',
    'admin.dialog.editUniversity': 'Изменить вуз',
    'admin.dialog.addUniversity': 'Добавить вуз',
    'admin.dialog.editMajor': 'Изменить специальность',
    'admin.dialog.addMajor': 'Добавить специальность',
    'admin.dialog.editNews': 'Изменить новость',
    'admin.dialog.publishNews': 'Опубликовать новость',
    'admin.dialog.editPage': 'Изменить страницу',
    'admin.dialog.addPage': 'Добавить страницу',
    'admin.dialog.editSetting': 'Изменить настройку',
    'admin.dialog.addSetting': 'Добавить настройку',
    'admin.dialog.editAdmissionResult': 'Изменить результат зачисления',
    'admin.dialog.addAdmissionResult': 'Добавить результат зачисления',
    'admin.dialog.editAcademicResult': 'Изменить запись оценок',
    'admin.dialog.addAcademicResult': 'Добавить запись оценок',
    'admin.dialog.replyConsultation': 'Ответить на консультацию',
    'admin.dialog.reviewApplication': 'Проверить заявку',
    'admin.field.name': 'Название',
    'admin.field.institutionType': 'Тип вуза',
    'admin.field.universityImages': 'Изображения вуза',
    'admin.field.majorCode': 'Код специальности',
    'admin.field.majorName': 'Название специальности',
    'admin.field.cutOffScore': 'Проходной балл',
    'admin.field.enrollmentQuota': 'План приема',
    'admin.field.majorCoverImages': 'Обложки специальности',
    'admin.field.curriculum': 'Учебный план',
    'admin.field.newsPicture': 'Изображение новости',
    'admin.field.picture1': 'Изображение 1',
    'admin.field.picture2': 'Изображение 2',
    'admin.field.picture3': 'Изображение 3',
    'admin.field.settingKey': 'Ключ настройки',
    'admin.field.settingValue': 'Значение настройки',
    'admin.field.resultStatus': 'Статус результата',
    'admin.field.gradeEvaluation': 'Оценивание',
    'admin.field.reportContent': 'Содержание отчета',
    'admin.field.studentQuestion': 'Вопрос студента',
    'admin.field.studentNo': 'Номер студента',
    'admin.field.password': 'Пароль',
    'admin.field.studentName': 'Имя',
    'admin.field.avatar': 'Путь аватара',
    'admin.field.gender': 'Пол',
    'admin.field.college': 'Факультет',
    'admin.field.contactNumber': 'Телефон',
    'admin.field.score': 'Балл',
    'admin.field.reviewComment': 'Комментарий проверки'
  }
}

export const useLanguageStore = defineStore('admin-language', () => {
  const current = ref<LanguageCode>(normalizeLanguage(localStorage.getItem(STORAGE_KEY)))

  const setLanguage = (value: LanguageCode) => {
    current.value = value
    localStorage.setItem(STORAGE_KEY, value)
    document.documentElement.lang = htmlLang[value]
  }

  const t = (key: string, params: Record<string, string | number> = {}) => {
    const template = messages[current.value][key] ?? messages.zh[key] ?? key
    return Object.entries(params).reduce(
      (text, [name, value]) => text.split(`{${name}}`).join(String(value)),
      template
    )
  }

  setLanguage(current.value)

  return {
    current,
    options: languageOptions,
    setLanguage,
    t
  }
})
