import { defineStore } from 'pinia'
import { ref } from 'vue'

export type LanguageCode = 'zh' | 'en' | 'ru'

export const languageOptions = [
  { code: 'zh', label: '中文' },
  { code: 'en', label: 'English' },
  { code: 'ru', label: 'Русский' }
] as const

const STORAGE_KEY = 'university.portal.language'

const htmlLang: Record<LanguageCode, string> = {
  zh: 'zh-CN',
  en: 'en-US',
  ru: 'ru-RU'
}

const normalizeLanguage = (value: string | null): LanguageCode => {
  if (value === 'en' || value === 'ru') {
    return value
  }
  return 'zh'
}

const messages: Record<LanguageCode, Record<string, string>> = {
  zh: {
    'language.label': '语言',
    'brand.name': 'LM 网站',
    'nav.universities': '院校',
    'nav.majors': '专业',
    'nav.news': '资讯',
    'nav.about': '关于我们',
    'nav.studentCenter': '学生中心',
    'common.loading': '正在加载...',
    'common.search': '搜索',
    'common.searching': '搜索中...',
    'common.viewDetails': '查看详情',
    'common.viewAll': '查看全部',
    'common.moreNews': '更多资讯',
    'common.previousPage': '上一页',
    'common.nextPage': '下一页',
    'common.pageInfo': '第 {page} 页，共 {total} 条',
    'common.noImage': '暂无图片',
    'common.noIntro': '暂无简介',
    'common.noContent': '暂无内容',
    'common.noContact': '暂无联系方式',
    'common.pendingDuration': '学制待定',
    'common.operationFailed': '操作失败，请稍后重试',
    'common.logout': '退出登录',
    'home.eyebrow': '升学规划门户',
    'home.title': '欢迎使用LM 网站',
    'home.subtitle': '浏览院校与专业，查看招生资讯。登录后可以提交报名、收藏目标，并在学生中心跟踪审核结果、录取信息和成绩。',
    'home.browseUniversities': '浏览院校',
    'home.viewMajors': '查看专业',
    'home.universityCount': '院校数据',
    'home.majorCount': '专业方向',
    'home.newsCount': '平台资讯',
    'home.featuredUniversities': '热门院校',
    'home.featuredEyebrow': '推荐院校',
    'home.latestNews': '最新资讯',
    'home.latestNewsEyebrow': '最新资讯',
    'home.noUniversities': '暂无院校数据。',
    'home.noNews': '暂无资讯内容。',
    'home.readFull': '查看完整内容',
    'login.eyebrow': '升学从这里开始',
    'login.title': '登录后管理你的升学选择',
    'login.subtitle': '浏览院校、比较专业、跟踪报名审核，并在学生中心集中查看录取与成绩信息。',
    'login.studentAccess': '学生入口',
    'login.formTitle': '学生登录',
    'login.formCaption': '使用学号和密码登录。',
    'login.studentNo': '学号',
    'login.password': '密码',
    'login.studentNoPlaceholder': '请输入学号',
    'login.passwordPlaceholder': '请输入密码',
    'login.submit': '进入学生中心',
    'login.submitting': '登录中...',
    'login.error': '登录失败，请检查学号和密码',
    'login.band.admissions': '招生报名',
    'login.band.majors': '专业选择',
    'login.band.scholarships': '奖学金',
    'login.band.results': '录取结果',
    'universities.eyebrow': '院校目录',
    'universities.title': '院校库',
    'universities.subtitle': '按名称和省份筛选院校，查看招生信息和开设专业，登录后可提交报名或收藏。',
    'universities.keyword': '搜索院校名称',
    'universities.allProvinces': '全部省份',
    'universities.defaultType': '院校',
    'universities.defaultTier': '综合',
    'universities.empty': '没有找到匹配的院校。',
    'universities.loading': '正在加载院校...',
    'majors.eyebrow': '专业目录',
    'majors.title': '专业库',
    'majors.subtitle': '筛选专业代码、名称和学制信息，登录后可直接提交专业报名或收藏感兴趣的专业。',
    'majors.keyword': '搜索专业名称或代码',
    'majors.cutoff': '分数线',
    'majors.quota': '计划',
    'majors.empty': '没有找到匹配的专业。',
    'majors.loading': '正在加载专业...',
    'news.eyebrow': '校园资讯',
    'news.title': '平台资讯',
    'news.subtitle': '查看招生动态、院校公告和学习规划内容。',
    'news.keyword': '搜索资讯标题',
    'news.empty': '没有找到匹配的资讯。',
    'news.loading': '正在加载资讯...',
    'newsDetail.loading': '正在加载资讯...',
    'newsDetail.notFound': '未找到资讯内容。',
    'newsDetail.fallbackEyebrow': '资讯',
    'page.about': '关于我们',
    'page.systemIntro': '系统介绍',
    'page.loading': '正在加载页面...',
    'page.notFound': '未找到页面内容。',
    'detail.loadingUniversity': '正在加载院校信息...',
    'detail.universityNotFound': '未找到院校信息。',
    'detail.universityMajors': '该院校专业',
    'detail.majorsEyebrow': '专业',
    'detail.universityTypeFallback': '院校',
    'detail.noUniversityMajors': '该院校暂未配置专业信息。',
    'detail.applyUniversity': '报名该院校',
    'detail.universitySubmitted': '院校报名已提交，请在学生中心查看审核状态。',
    'detail.loadingMajor': '正在加载专业信息...',
    'detail.majorNotFound': '未找到专业信息。',
    'detail.applyMajor': '报名该专业',
    'detail.majorSubmitted': '专业报名已提交，请在学生中心查看审核状态。',
    'detail.favorite': '收藏',
    'detail.favoriting': '收藏中...',
    'detail.submitting': '提交中...',
    'detail.favoriteAdded': '已加入收藏，可在学生中心查看。',
    'detail.alreadyFavorited': '已经收藏过了',
    'detail.tier': '层次',
    'detail.phone': '电话',
    'detail.website': '官网',
    'detail.duration': '修业年限',
    'detail.cutoff': '分数线',
    'detail.quota': '招生计划',
    'detail.curriculumEmpty': '暂无培养方案。',
    'student.eyebrow': '学生中心',
    'student.titleFallback': '学生中心',
    'student.subtitle': '集中查看个人资料、报名审核、录取结果、成绩信息、收藏内容和咨询回复。',
    'student.refresh': '刷新数据',
    'student.refreshing': '刷新中...',
    'student.continueBrowse': '继续浏览院校',
    'student.profile': '个人资料',
    'student.studentNo': '学号',
    'student.college': '学院',
    'student.phone': '电话',
    'student.consultation': '提交咨询',
    'student.questionPlaceholder': '请输入想咨询的问题',
    'student.submitQuestion': '提交咨询',
    'student.submittingQuestion': '提交中...',
    'student.universityApplications': '院校报名',
    'student.majorApplications': '专业报名',
    'student.results': '录取与成绩',
    'student.favorites': '我的收藏',
    'student.consultationReplies': '咨询回复',
    'student.recommendations': '智能推荐',
    'student.recommendationLoading': '正在生成成绩推荐...',
    'student.latestGrade': '当前最新成绩：{grade} 分',
    'student.recommendedUniversities': '推荐院校',
    'student.recommendedMajors': '推荐专业',
    'student.cutoff': '分数线',
    'student.margin': '高出',
    'student.quota': '计划',
    'student.noRecommendations': '暂无可推荐的院校或专业，请先确认成绩和专业分数线数据。',
    'student.waitingReview': '等待审核结果',
    'student.noUniversityApplications': '还没有院校报名记录。',
    'student.noMajorApplications': '还没有专业报名记录。',
    'student.noResults': '暂无录取或成绩信息。',
    'student.noFavorites': '还没有收藏内容，浏览院校或专业后可以点击收藏。',
    'student.noConsultations': '暂无咨询记录。',
    'student.admissionResult': '录取结果：{status}',
    'student.noFeedback': '暂无反馈',
    'student.reportFallback': '成绩报告',
    'student.noEvaluation': '暂无评价',
    'student.replyPending': '管理员尚未回复',
    'student.cancelFavorite': '取消收藏',
    'student.cancelingFavorite': '取消中...',
    'status.APPROVED': '已通过',
    'status.REJECTED': '已拒绝',
    'status.PENDING': '待审核',
    'favorite.university': '院校',
    'favorite.major': '专业',
    'favorite.news': '资讯',
    'favorite.default': '收藏',
    'ai.open': 'AI',
    'ai.close': '关闭',
    'ai.eyebrow': '智能升学助手',
    'ai.title': 'AI 对话',
    'ai.newChat': '新会话',
    'ai.deleteChat': '删除会话',
    'ai.deleteConfirm': '确定删除这个 AI 会话吗？',
    'ai.empty': '可以咨询院校、专业、资讯，也可以让系统结合你的报名和收藏给出推荐。',
    'ai.you': '你',
    'ai.assistant': 'AI 助手',
    'ai.placeholder': '输入你的问题...',
    'ai.sending': '回复中',
    'ai.send': '发送'
  },
  en: {
    'language.label': 'Language',
    'brand.name': 'LM',
    'nav.universities': 'Universities',
    'nav.majors': 'Majors',
    'nav.news': 'News',
    'nav.about': 'About',
    'nav.studentCenter': 'Student Center',
    'common.loading': 'Loading...',
    'common.search': 'Search',
    'common.searching': 'Searching...',
    'common.viewDetails': 'View Details',
    'common.viewAll': 'View All',
    'common.moreNews': 'More News',
    'common.previousPage': 'Previous',
    'common.nextPage': 'Next',
    'common.pageInfo': 'Page {page}, {total} records',
    'common.noImage': 'No image',
    'common.noIntro': 'No introduction yet',
    'common.noContent': 'No content yet',
    'common.noContact': 'No contact available',
    'common.pendingDuration': 'Duration pending',
    'common.operationFailed': 'Operation failed. Please try again later.',
    'common.logout': 'Log Out',
    'home.eyebrow': 'Admission Planning Portal',
    'home.title': 'Welcome to LM Website',
    'home.subtitle': 'Browse universities and majors, read admission news, submit applications after signing in, save targets, and track review results, admission information, and grades.',
    'home.browseUniversities': 'Browse Universities',
    'home.viewMajors': 'View Majors',
    'home.universityCount': 'Universities',
    'home.majorCount': 'Major Options',
    'home.newsCount': 'Portal News',
    'home.featuredUniversities': 'Featured Universities',
    'home.featuredEyebrow': 'Featured Universities',
    'home.latestNews': 'Latest News',
    'home.latestNewsEyebrow': 'Latest News',
    'home.noUniversities': 'No university data yet.',
    'home.noNews': 'No news content yet.',
    'home.readFull': 'Read full content',
    'login.eyebrow': 'Future Starts Here',
    'login.title': 'Sign in to manage your admission choices',
    'login.subtitle': 'Browse universities, compare majors, track application reviews, and view admission and grade information in the student center.',
    'login.studentAccess': 'Student Access',
    'login.formTitle': 'Student Login',
    'login.formCaption': 'Use your student number and password.',
    'login.studentNo': 'Student No.',
    'login.password': 'Password',
    'login.studentNoPlaceholder': 'Enter student number',
    'login.passwordPlaceholder': 'Enter password',
    'login.submit': 'Enter Student Center',
    'login.submitting': 'Signing in...',
    'login.error': 'Login failed. Please check the student number and password.',
    'login.band.admissions': 'Admissions',
    'login.band.majors': 'Majors',
    'login.band.scholarships': 'Scholarships',
    'login.band.results': 'Results',
    'universities.eyebrow': 'University Catalog',
    'universities.title': 'University Library',
    'universities.subtitle': 'Filter universities by name and province, review admission information and majors, and submit applications or favorites after signing in.',
    'universities.keyword': 'Search university name',
    'universities.allProvinces': 'All provinces',
    'universities.defaultType': 'University',
    'universities.defaultTier': 'General',
    'universities.empty': 'No matching universities found.',
    'universities.loading': 'Loading universities...',
    'majors.eyebrow': 'Major Directory',
    'majors.title': 'Major Library',
    'majors.subtitle': 'Filter majors by code, name, and duration. After signing in, submit major applications or save interested majors.',
    'majors.keyword': 'Search major name or code',
    'majors.cutoff': 'Cutoff',
    'majors.quota': 'Quota',
    'majors.empty': 'No matching majors found.',
    'majors.loading': 'Loading majors...',
    'news.eyebrow': 'Campus News',
    'news.title': 'Portal News',
    'news.subtitle': 'Read admission updates, university announcements, and study planning content.',
    'news.keyword': 'Search news title',
    'news.empty': 'No matching news found.',
    'news.loading': 'Loading news...',
    'newsDetail.loading': 'Loading news...',
    'newsDetail.notFound': 'News content not found.',
    'newsDetail.fallbackEyebrow': 'News',
    'page.about': 'About Us',
    'page.systemIntro': 'System Intro',
    'page.loading': 'Loading page...',
    'page.notFound': 'Page content not found.',
    'detail.loadingUniversity': 'Loading university information...',
    'detail.universityNotFound': 'University information not found.',
    'detail.universityMajors': 'Majors at this university',
    'detail.majorsEyebrow': 'Majors',
    'detail.universityTypeFallback': 'University',
    'detail.noUniversityMajors': 'No major information has been configured for this university.',
    'detail.applyUniversity': 'Apply to this university',
    'detail.universitySubmitted': 'University application submitted. Check the review status in the student center.',
    'detail.loadingMajor': 'Loading major information...',
    'detail.majorNotFound': 'Major information not found.',
    'detail.applyMajor': 'Apply to this major',
    'detail.majorSubmitted': 'Major application submitted. Check the review status in the student center.',
    'detail.favorite': 'Favorite',
    'detail.favoriting': 'Saving...',
    'detail.submitting': 'Submitting...',
    'detail.favoriteAdded': 'Added to favorites. You can view it in the student center.',
    'detail.alreadyFavorited': 'Already favorited',
    'detail.tier': 'Tier',
    'detail.phone': 'Phone',
    'detail.website': 'Website',
    'detail.duration': 'Duration',
    'detail.cutoff': 'Cutoff',
    'detail.quota': 'Enrollment quota',
    'detail.curriculumEmpty': 'No curriculum plan yet.',
    'student.eyebrow': 'Student Center',
    'student.titleFallback': 'Student Center',
    'student.subtitle': 'View profile data, application reviews, admission results, grade information, favorites, and consultation replies in one place.',
    'student.refresh': 'Refresh Data',
    'student.refreshing': 'Refreshing...',
    'student.continueBrowse': 'Continue Browsing',
    'student.profile': 'Profile',
    'student.studentNo': 'Student No.',
    'student.college': 'College',
    'student.phone': 'Phone',
    'student.consultation': 'Submit Consultation',
    'student.questionPlaceholder': 'Enter your question',
    'student.submitQuestion': 'Submit Consultation',
    'student.submittingQuestion': 'Submitting...',
    'student.universityApplications': 'University Applications',
    'student.majorApplications': 'Major Applications',
    'student.results': 'Admission and Grades',
    'student.favorites': 'My Favorites',
    'student.consultationReplies': 'Consultation Replies',
    'student.recommendations': 'Smart Recommendations',
    'student.recommendationLoading': 'Generating grade-based recommendations...',
    'student.latestGrade': 'Latest grade: {grade}',
    'student.recommendedUniversities': 'Recommended Universities',
    'student.recommendedMajors': 'Recommended Majors',
    'student.cutoff': 'Cutoff',
    'student.margin': 'Margin',
    'student.quota': 'Quota',
    'student.noRecommendations': 'No eligible universities or majors yet. Please confirm grade and cutoff data.',
    'student.waitingReview': 'Waiting for review result',
    'student.noUniversityApplications': 'No university applications yet.',
    'student.noMajorApplications': 'No major applications yet.',
    'student.noResults': 'No admission or grade information yet.',
    'student.noFavorites': 'No favorites yet. Browse universities or majors and save items you like.',
    'student.noConsultations': 'No consultation records yet.',
    'student.admissionResult': 'Admission result: {status}',
    'student.noFeedback': 'No feedback yet',
    'student.reportFallback': 'Grade report',
    'student.noEvaluation': 'No evaluation yet',
    'student.replyPending': 'Administrator has not replied yet',
    'student.cancelFavorite': 'Remove Favorite',
    'student.cancelingFavorite': 'Removing...',
    'status.APPROVED': 'Approved',
    'status.REJECTED': 'Rejected',
    'status.PENDING': 'Pending',
    'favorite.university': 'University',
    'favorite.major': 'Major',
    'favorite.news': 'News',
    'favorite.default': 'Favorite',
    'ai.open': 'AI',
    'ai.close': 'Close',
    'ai.eyebrow': 'Smart Admission Assistant',
    'ai.title': 'AI Chat',
    'ai.newChat': 'New chat',
    'ai.deleteChat': 'Delete chat',
    'ai.deleteConfirm': 'Delete this AI conversation?',
    'ai.empty': 'Ask about universities, majors, and news, or request recommendations based on your own applications and favorites.',
    'ai.you': 'You',
    'ai.assistant': 'AI Assistant',
    'ai.placeholder': 'Type your question...',
    'ai.sending': 'Replying',
    'ai.send': 'Send'
  },
  ru: {
    'language.label': 'Язык',
    'brand.name': 'Сайт LM.',
    'nav.universities': 'Вузы',
    'nav.majors': 'Специальности',
    'nav.news': 'Новости',
    'nav.about': 'О нас',
    'nav.studentCenter': 'Кабинет студента',
    'common.loading': 'Загрузка...',
    'common.search': 'Поиск',
    'common.searching': 'Поиск...',
    'common.viewDetails': 'Подробнее',
    'common.viewAll': 'Смотреть все',
    'common.moreNews': 'Больше новостей',
    'common.previousPage': 'Назад',
    'common.nextPage': 'Вперед',
    'common.pageInfo': 'Страница {page}, всего {total}',
    'common.noImage': 'Нет изображения',
    'common.noIntro': 'Описание пока отсутствует',
    'common.noContent': 'Контента пока нет',
    'common.noContact': 'Контакты отсутствуют',
    'common.pendingDuration': 'Срок обучения уточняется',
    'common.operationFailed': 'Операция не выполнена. Повторите позже.',
    'common.logout': 'Выйти',
    'home.eyebrow': 'Портал планирования поступления',
    'home.title': 'Добро пожаловать на сайт LM.',
    'home.subtitle': 'Просматривайте вузы и специальности, читайте новости приема, после входа подавайте заявки, сохраняйте цели и отслеживайте проверки, зачисление и оценки.',
    'home.browseUniversities': 'Смотреть вузы',
    'home.viewMajors': 'Смотреть специальности',
    'home.universityCount': 'Вузы',
    'home.majorCount': 'Направления',
    'home.newsCount': 'Новости портала',
    'home.featuredUniversities': 'Популярные вузы',
    'home.featuredEyebrow': 'Рекомендуемые вузы',
    'home.latestNews': 'Последние новости',
    'home.latestNewsEyebrow': 'Последние новости',
    'home.noUniversities': 'Данных о вузах пока нет.',
    'home.noNews': 'Новостей пока нет.',
    'home.readFull': 'Читать полностью',
    'login.eyebrow': 'Будущее начинается здесь',
    'login.title': 'Войдите, чтобы управлять выбором поступления',
    'login.subtitle': 'Просматривайте вузы, сравнивайте специальности, отслеживайте заявки и смотрите зачисление и оценки в кабинете студента.',
    'login.studentAccess': 'Вход для студента',
    'login.formTitle': 'Вход студента',
    'login.formCaption': 'Используйте номер студента и пароль.',
    'login.studentNo': 'Номер студента',
    'login.password': 'Пароль',
    'login.studentNoPlaceholder': 'Введите номер студента',
    'login.passwordPlaceholder': 'Введите пароль',
    'login.submit': 'Войти в кабинет',
    'login.submitting': 'Вход...',
    'login.error': 'Не удалось войти. Проверьте номер студента и пароль.',
    'login.band.admissions': 'Прием',
    'login.band.majors': 'Специальности',
    'login.band.scholarships': 'Стипендии',
    'login.band.results': 'Результаты',
    'universities.eyebrow': 'Каталог вузов',
    'universities.title': 'Каталог вузов',
    'universities.subtitle': 'Фильтруйте вузы по названию и провинции, смотрите информацию о приеме и специальностях, после входа подавайте заявки или добавляйте в избранное.',
    'universities.keyword': 'Поиск по названию вуза',
    'universities.allProvinces': 'Все провинции',
    'universities.defaultType': 'Вуз',
    'universities.defaultTier': 'Общий',
    'universities.empty': 'Подходящие вузы не найдены.',
    'universities.loading': 'Загрузка вузов...',
    'majors.eyebrow': 'Каталог специальностей',
    'majors.title': 'Каталог специальностей',
    'majors.subtitle': 'Фильтруйте специальности по коду, названию и сроку обучения. После входа можно подать заявку или сохранить специальность.',
    'majors.keyword': 'Поиск по специальности или коду',
    'majors.cutoff': 'Проходной балл',
    'majors.quota': 'План',
    'majors.empty': 'Подходящие специальности не найдены.',
    'majors.loading': 'Загрузка специальностей...',
    'news.eyebrow': 'Новости кампуса',
    'news.title': 'Новости портала',
    'news.subtitle': 'Читайте новости приема, объявления вузов и материалы по планированию учебы.',
    'news.keyword': 'Поиск по заголовку новости',
    'news.empty': 'Подходящие новости не найдены.',
    'news.loading': 'Загрузка новостей...',
    'newsDetail.loading': 'Загрузка новости...',
    'newsDetail.notFound': 'Новость не найдена.',
    'newsDetail.fallbackEyebrow': 'Новость',
    'page.about': 'О нас',
    'page.systemIntro': 'О системе',
    'page.loading': 'Загрузка страницы...',
    'page.notFound': 'Страница не найдена.',
    'detail.loadingUniversity': 'Загрузка информации о вузе...',
    'detail.universityNotFound': 'Информация о вузе не найдена.',
    'detail.universityMajors': 'Специальности этого вуза',
    'detail.majorsEyebrow': 'Специальности',
    'detail.universityTypeFallback': 'Вуз',
    'detail.noUniversityMajors': 'Для этого вуза специальности пока не настроены.',
    'detail.applyUniversity': 'Подать заявку в вуз',
    'detail.universitySubmitted': 'Заявка в вуз отправлена. Статус проверки доступен в кабинете студента.',
    'detail.loadingMajor': 'Загрузка специальности...',
    'detail.majorNotFound': 'Информация о специальности не найдена.',
    'detail.applyMajor': 'Подать заявку на специальность',
    'detail.majorSubmitted': 'Заявка на специальность отправлена. Статус проверки доступен в кабинете студента.',
    'detail.favorite': 'В избранное',
    'detail.favoriting': 'Сохранение...',
    'detail.submitting': 'Отправка...',
    'detail.favoriteAdded': 'Добавлено в избранное. Можно посмотреть в кабинете студента.',
    'detail.alreadyFavorited': 'Уже в избранном',
    'detail.tier': 'Уровень',
    'detail.phone': 'Телефон',
    'detail.website': 'Сайт',
    'detail.duration': 'Срок обучения',
    'detail.cutoff': 'Проходной балл',
    'detail.quota': 'План приема',
    'detail.curriculumEmpty': 'Учебный план пока отсутствует.',
    'student.eyebrow': 'Кабинет студента',
    'student.titleFallback': 'Кабинет студента',
    'student.subtitle': 'Просматривайте профиль, проверки заявок, результаты зачисления, оценки, избранное и ответы на вопросы в одном месте.',
    'student.refresh': 'Обновить данные',
    'student.refreshing': 'Обновление...',
    'student.continueBrowse': 'Продолжить просмотр',
    'student.profile': 'Профиль',
    'student.studentNo': 'Номер студента',
    'student.college': 'Факультет',
    'student.phone': 'Телефон',
    'student.consultation': 'Отправить вопрос',
    'student.questionPlaceholder': 'Введите вопрос',
    'student.submitQuestion': 'Отправить вопрос',
    'student.submittingQuestion': 'Отправка...',
    'student.universityApplications': 'Заявки в вузы',
    'student.majorApplications': 'Заявки на специальности',
    'student.results': 'Зачисление и оценки',
    'student.favorites': 'Избранное',
    'student.consultationReplies': 'Ответы на вопросы',
    'student.recommendations': 'Умные рекомендации',
    'student.recommendationLoading': 'Формируем рекомендации по оценкам...',
    'student.latestGrade': 'Последняя оценка: {grade}',
    'student.recommendedUniversities': 'Рекомендуемые вузы',
    'student.recommendedMajors': 'Рекомендуемые специальности',
    'student.cutoff': 'Проходной балл',
    'student.margin': 'Запас',
    'student.quota': 'План',
    'student.noRecommendations': 'Подходящих вузов или специальностей пока нет. Проверьте оценки и проходные баллы.',
    'student.waitingReview': 'Ожидание результата проверки',
    'student.noUniversityApplications': 'Заявок в вузы пока нет.',
    'student.noMajorApplications': 'Заявок на специальности пока нет.',
    'student.noResults': 'Информации о зачислении или оценках пока нет.',
    'student.noFavorites': 'Избранного пока нет. Просматривайте вузы или специальности и сохраняйте интересное.',
    'student.noConsultations': 'Вопросов пока нет.',
    'student.admissionResult': 'Результат зачисления: {status}',
    'student.noFeedback': 'Отзыва пока нет',
    'student.reportFallback': 'Отчет об оценках',
    'student.noEvaluation': 'Оценки пока нет',
    'student.replyPending': 'Администратор еще не ответил',
    'student.cancelFavorite': 'Удалить из избранного',
    'student.cancelingFavorite': 'Удаление...',
    'status.APPROVED': 'Одобрено',
    'status.REJECTED': 'Отклонено',
    'status.PENDING': 'На проверке',
    'favorite.university': 'Вуз',
    'favorite.major': 'Специальность',
    'favorite.news': 'Новость',
    'favorite.default': 'Избранное',
    'ai.open': 'AI',
    'ai.close': 'Закрыть',
    'ai.eyebrow': 'Умный помощник по поступлению',
    'ai.title': 'AI-чат',
    'ai.newChat': 'Новый чат',
    'ai.deleteChat': 'Удалить чат',
    'ai.deleteConfirm': 'Удалить этот AI-диалог?',
    'ai.empty': 'Задавайте вопросы о вузах, специальностях и новостях или попросите рекомендации на основе ваших заявок и избранного.',
    'ai.you': 'Вы',
    'ai.assistant': 'AI-помощник',
    'ai.placeholder': 'Введите вопрос...',
    'ai.sending': 'Ответ идет',
    'ai.send': 'Отправить'
  }
}

export const useLanguageStore = defineStore('portal-language', () => {
  const current = ref<LanguageCode>(normalizeLanguage(localStorage.getItem(STORAGE_KEY)))

  const setLanguage = (value: LanguageCode) => {
    current.value = value
    localStorage.setItem(STORAGE_KEY, value)
    document.documentElement.lang = htmlLang[value]
  }

  const t = (key: string, params: Record<string, string | number> = {}) => {
    const template = messages[current.value][key] ?? messages.zh[key] ?? key
    return Object.entries(params).reduce(
      (text, [name, value]) => text.split(`{${name}}`).join(String(value)),
      template
    )
  }

  setLanguage(current.value)

  return {
    current,
    options: languageOptions,
    setLanguage,
    t
  }
})
